### ISSUE TITLE
Takes a screenshot of elements picked out by css/xpath selector.

### ISSUE THREAD

**Issue by MitsuhaMiyamizu** [ashbythorpe/selenider#10]
Happy holidays,

1. ```chromote``` supports screenshot of specific elements picked out by css/xpath selector. See https://github.com/rstudio/chromote for details. After searching for the function ```take_screenshot``` of ```selenider```, I didn't find any option for the need.
2. ```selenider_session(quite = F)``` seems not functional because after executing this, the chromote still run chromium in headless mode, chromium didn't show up in front of me. It makes debug process more difficult.

Regards.

**Comment by ashbythorpe** [comment]
> 2. `selenider_session(quite = F)` seems not functional because after executing this, the chromote still run chromium in headless mode, chromium didn't show up in front of me. It makes debug process more difficult.

Try `selenider_session(view = TRUE)`.

I'll probably rename this argument to something more clear (like `headless`) in a future release.

**Comment by ashbythorpe** [comment]
> 1. `chromote` supports screenshot of specific elements picked out by css/xpath selector. See https://github.com/rstudio/chromote for details. After searching for the function `take_screenshot` of `selenider`, I didn't find any option for the need.

I was unsure about implementing this originally because I wasn't sure how useful it would be, but I would be open to adding this feature now. I need to investigate whether this is possible in Selenium as well.

For now, you can access the `ChromoteSession` from a `selenider_session` using `session$driver`, so you can quite easily take a screenshot using the chromote `screenshot()` method directly:

``` r
session$driver$screenshot(selector = "YOUR SELECTOR")
```

**Comment by MitsuhaMiyamizu** [comment]
Solved, issue will be closed right away.
