### ISSUE TITLE
withr::local_tempfile() in examples may not be WAI

### ISSUE THREAD

**Issue by MichaelChirico** [ashbythorpe/selenider#11]
See https://github.com/r-lib/withr/issues/256 for some discussion.

There's no error in your package because the {withr} usage is not behind an `@examplesIf` condition, but still I was surprised to learn that the cleanup of the temp file doesn't happen when I'd've thought in examples.

Feel free to close this informational issue.

**Comment by ashbythorpe** [comment]
Thanks for this. I think I'm just going to set `withr.hook_source` to `TRUE` by default, since I'm not too worried about the performance implications. I've been having issues with withr and examples before, notably that withr does not work inside pkgdown examples, even with the `withr.hook_source` option (see https://github.com/r-lib/withr/issues/230).
